app/models.py
from . import db, login_manager
from flask_login import UserMixin
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key = True)
    email = db.Column(db.String(255), unique = True, index = True)
    username = db.Column(db.String(200))
    pass_secure = db.Column(db.String(255))
    name = db.Column(db.String(100))

    def password(self, password):
        self.pass_secure = generate_password_hash(password)
    

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)
    
    def __repr__(self):
        return f'{self.username}'


class Tale(db.Model):
    __tablename__ = 'tales'
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(255))
    author = db.Column(db.String(255), unique = True)
    blog = db.Column(db.Text, nullable = False)


    @classmethod
    def get_tales(cls,id):
        blogs = Tale.query.order_by(tale_id=id).desc().all()
        return blogs

    def __repr__(self):
        return f'Tale {self.blog_content}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import Required
from flask_login import current_user

class CreateBlog(FlaskForm):
    title = StringField('Title', validators=[Required()])
    content = TextAreaField('Content', validators=[Required()])
    author = StringField('Author')
    comment = StringField('Comment')
    submit = SubmitField('Post')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Who is {{name}}?', validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from config import config_options
from flask import app
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

# from app import views

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_options[config_name])


    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from.requests import configure_request
    configure_request(app)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from .import views

app/main/views.py
from flask import render_template, abort, request, redirect, url_for, flash
from . import main
from .. import db
from app.models import Tale, User
from .forms import CreateBlog, UpdateProfile
from flask_login import login_required, current_user
from ..requests import random_quotes


@main.route('/', methods = ['GET', 'POST'])
def index():
    quotes = random_quotes()
    tales = Tale.query.all()
    return render_template('index.html', quotes = quotes, tales=tales)

@main.route('/tale/new', methods=['GET', 'POST'])
@login_required
def new_tale():
    form = CreateBlog()
    if form.validate_on_submit():
        print(form.title.data)
        tale = Tale(title =form.title.data, blog=form.content.data, author=current_user.name)
        db.session.add(tale)
        db.session.commit()
        flash('Your Blog-Tale has been created!', 'success')
        return redirect(url_for('main.index'))
    return render_template('create-blog.html', title='New_Tale', form=form)

@main.route('/profile/<name>')
@login_required
def profile(name):
    user = User.query.filter_by(username = name).first()

    if user is None:
        abort(404)
    return render_template('profile.html', user=user)


@main.route('/user/<name>/update',methods = ['Get', 'POST'])
@login_required
def update_profile(name):
    user = User.query.filter_by(username = name).first()
    if user is None:
        abort(404)

    form = UpdateProfile()
    
    if form.validate_on_submit():
        user.bio = form.bio.data


        db.session.add(user)
        db.session.commit()

        return redirect(url_for('main.profile', username=user.name))

    return render_template('profile/update.html', form = form)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">

    {% block head%} {% endblock %}
</head>
<body>
    {% block navbar %}
    {% include 'navbar.html' %}
    {% endblock%}

    {% block body %}
    {% block content %} {% endblock%}
    {% endblock%}    
</body>
</html>

app/templates/create-blog.html
{% extends "base.html" %}

{% block content %}

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">

    
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag()}}
        <fieldset class="form-group">
            <legend class="border-bottom md-4">New Blog</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label")}}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invisible")}}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span> {{error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                        {{form.title(class="form-control form-control-lg")}}
                    {% endif %}
                
            </div>
            
            <div class="form-group">
                {{ form.content.label(class="form-control-label")}}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invisible")}}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{error}}</span>
                        {%endfor %}
                    </div>
                {% else %}
                    {{form.content(class="form-control form-control-lg")}}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.author.label(class="form-control-label")}}
                {% if form.author.errors %}
                    {{ form.author(class="form-control form-control-lg is-invisible")}}
                    <div class="invalid-feedback">
                        {% for error in form.authot.errors %}
                            <span>{{error}}</span>
                        {%endfor %}
                    </div>
                {% else %}
                    {{form.author(class="form-control form-control-lg")}}
                {% endif %}
            </div>
            
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info")}}
        </div>
    </form>
</div>
</div>
</div>
{% endblock%}

app/templates/index.html
{% extends 'base.html'%}
{% block content%}
<link href="https://fonts.googleapis.com/css?family=Rajdhani|Ropa+Sans|Unna&display=swap" rel="stylesheet">
<div class="container">
    <div class="row">
        <div class="col-md-2" id="sidebar">
            <table>
                <tr>
                    <td class="b">
                        <img src="/static/images/b.png">
                    </td>
                </tr>
                <tr>
                    <td class="l">
                            <img src="/static/images/l.png">
                    </td>
                </tr>
                <tr>
                    <td class="o">
                            <img src="/static/images/o.png">
                    </td>
                </tr>
                <tr>
                    <td class="g">
                            <img src="/static/images/g.png">
                    </td>
                </tr>
            </table>
        </div>
        <div class="col-md-8">

            {% for tale in tales %}

            <div class="card">
                <div class="card-header">
                    <h4>
                            Title: {{tale.title}}
                    </h4>
                </div>
                <div class="card-body">


                    <p class="card-text"> {{tale.blog}}</p>
                    <p class="card-text">By: {{tale.author}}</p>
                </div>
                <div class="card-footer">
                    
                </div>
                </div>
    
                {% endfor %}
        </div>
        
        <div class="col-md-2" id="quotes">
            <h1>Random Quotes</h1>
            <p>{{quotes.quote}}</p>
            <p>By: {{quotes.author}}</p>
            <a href="{{quotes.permalink}}">
                <p>View</p>
            </a>
        </div>
    </div>
</div>

{% endblock%}

app/templates/login.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-danger">
                
                {{ message }}
            </div>
            {% endfor %}
            {{wtf.quick_form(loginForm,button_map={'submit':'success'})}}
            <button type="submit" class="close" data-dismiss="alert">&times;</button>
            <p>Don't have an account? <a href= "{{url_for('auth.register')}}">Subscribe here</a></p>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

{% endblock %}

app/templates/navbar.html
<!-- <ul class="nav navbar-nav navbar-right">
    {% if current_user.is_authenticated %}
    <li style="color:white;padding:15px;">{{current_user.username}}</li>
    <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
    {% else %}
    <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
    {%endif%}
  </ul> -->

<link href="https://fonts.googleapis.com/css?family=Cute+Font|Turret+Road&display=swap" rel="stylesheet">

<div class="container-fluid" id="top">
  <div class="row">
    <div class="col-md-5"></div>
    <div class="col-md-2" id="header">
      <img src="/static/images/bg.jpeg">
    </div>
    <div class="col-md-5"></div>

  </div>
</div>
<div class="container">
<div class="row" col-md-12>
  <div class="col-md-12">
<nav class="mb-1 navbar navbar-expand-lg navbar-light info-color" id="navy">
  <a href="{{ url_for('main.index') }}" class="navbar-item">HOME</a>
  
  
  <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        {% if not current_user.is_authenticated %}
        <a href="{{ url_for('auth.register') }}" class="navbar-item">
          <i class="signup"></i>SIGN-UP</a>
        {% endif %}
      </li>

      <li class="nav-item">
        {% if not current_user.is_authenticated %}

        <a href="{{ url_for('auth.login') }}" class="navebar-item">
          <i class="login"></i> LOGIN</a>
        {% endif %}
      </li>



      <li class="nav-item">
        {% if current_user.is_authenticated %}
        <a href ="{{url_for('main.new_tale') }}" class = "navbar-item">
          <i class="user_account"></i> NEW TALE
          
        </a>
        <a href ="{{url_for('main.profile', name = current_user.username)}}" class = "navbar-item">
          <i class="user_account"></i> PROFILE
          <span class="sr-only">(current)</span>
        </a> 
        {% endif %}

      </li>
      <li class="nav-item">
        {% if current_user.is_authenticated %}
        <a href="{{url_for('auth.logout')}}" class="navbar-item">
          <i class="fab fa-instagram"></i> LOGOUT</a>
        {% endif%}
      </li>

    </ul>
  </div>
</nav>
</div>
</div>
</div>

app/templates/profile.html
{% extends 'base.html'%}
{% block content%}

<div class="container">
        <div class="row">
            <div class="col-md-2" id="sidebar">
                <table>
                    <tr>
                        <td class="b">
                            <img src="/static/images/b.png">
                        </td>
                    </tr>
                    <tr>
                        <td class="l">
                                <img src="/static/images/l.png">
                        </td>
                    </tr>
                    <tr>
                        <td class="o">
                                <img src="/static/images/o.png">
                        </td>
                    </tr>
                    <tr>
                        <td class="g">
                                <img src="/static/images/g.png">
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-md-8">
                <h4>{{username}}Update Your Profile</h4>
                
            </div>
            
            <div class="col-md-2" id="quotes">
                
            </div>
        </div>
    </div>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            {{wtf.quick_form(subscriptionForm,button_map={'submit':'success'})}}
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

{% endblock %}